# Rust code formatting configuration for TwoPassword

# General formatting options
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Struct and enum formatting
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20

# String formatting
format_strings = true
format_macro_matchers = true

# Comment formatting
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
comment_width = 80

# Control flow formatting
control_brace_style = "AlwaysSameLine"
indent_style = "Block"

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Miscellaneous
remove_nested_parens = true
use_small_heuristics = "Default"
newline_style = "Unix"